# Dockerfile para Django
FROM python:3.10

# Definir o diretório de trabalho
WORKDIR /app

# Copiar e instalar dependências
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o restante da aplicação
COPY . /app/

# Expor a porta que o Django usará
EXPOSE 8000

# Comando para iniciar o servidor Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
